name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: chmod u+x configure;./configure
    - name: cmake
      run: |
       cmake -S . -B build
       cd build && make
       
